carts/urls.py
from django.urls import path
from . views import cart ,add_cart,remove_cart,remove_cart_item,checkout

app_name = 'carts'

urlpatterns = [
    path('', cart ,name = 'cart'),
    path('add_cart/<int:product_id>/', add_cart ,name = 'add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', remove_cart ,name = 'remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', remove_cart_item ,name = 'remove_cart_item'),
    path('checkout/', checkout ,name = 'checkout'),
]

orders/urls.py
from django.urls import path
from .  import views

app_name = 'orders'

urlpatterns = [
    path('place_order/' , views.place_order , name='place_order'),
    path('payments/' , views.payments , name='payments'),
    path('order_complete/' , views.order_complete , name='order_complete'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('',views.ProductList.as_view(),name='product_list'),
    path('orderd_by_rating/',views.product_list_orderd_by_rating,name='product_list_orderd_by_rating'),
    path('orderd_by_created/',views.product_list_orderd_by_created , name='product_list_orderd_by_created'),
    path('orderd_by_popularty/',views.product_list_orderd_by_papularty , name='product_list_orderd_by_papularty'),
    path('orderd_by_price/',views.product_list_orderd_by_price , name='product_list_orderd_by_price'),
    path('orderd_by_highest price/',views.product_list_orderd_by_price2 , name='product_list_orderd_by_price2'),
    path('search/' , views.Search.as_view() , name = 'search'),
    path('result/' , views.search , name = 'result'),
    path('<slug:product_slug>/',views.product_detail ,name='product_detail'),
    path('<int:id>/like_or_dislike',views.like_or_unlike , name='like'),
    path('category/<int:id>/' , views.ProductByCategory.as_view() , name='product_by_category'),
    path('tags/<str:slug>/' , views.ProductByTags.as_view() , name='product_by_tags'),
    path('brand/<str:slug>/' , views.ProductByBrand.as_view() , name='product_by_brand'),
    path('submit_review/<int:product_id>/',views.submit_review ,name='submit_review'),
    path('&product_by_price/' , views.product_by_price , name = 'product_by_price'),
    path('&product_by_variation/' , views.product_by_variation , name = 'product_by_variation'),
]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('' , include('settings.urls' , namespace='home')),
    path('product/' , include('product.urls',namespace='product')),
    path('cart/' , include('carts.urls' , namespace='carts')),
    path('orders/' , include('orders.urls' )),
]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    payment_id = models.CharField( max_length=100)
    payment_method = models.CharField( max_length=100)
    payment_paid = models.CharField( max_length=100)
    status = models.CharField( max_length=100)
    created_at = models.DateTimeField( auto_now_add=True)

    def __str__(self):
        return self.payment_id
    

class Order(models.Model):
    STATUS = (
        ('New','New'),
        ('Accepted','Accepted'),
        ('Completed','Completed'),
        ('Cancelled','Cancelled'),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL , null=True)
    payment = models.ForeignKey(Payment,  on_delete=models.SET_NULL ,blank=True , null=True)
    order_number = models.CharField(max_length=50)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=50,blank=True)
    email = models.EmailField( max_length=254)
    address_line_1 = models.CharField( max_length=50)
    address_line_2 = models.CharField( max_length=50 , blank=True)
    country = models.CharField( max_length=50 )
    state = models.CharField( max_length=50 )
    city = models.CharField( max_length=50 )
    order_note = models.CharField( max_length=1000 , blank=True)
    order_total = models.FloatField()
    tax = models.FloatField()
    status = models.CharField(choices=STATUS,default='New' , max_length=15)
    ip = models.CharField(max_length=50  ,blank=True)
    is_orderd = models.BooleanField(default=False)
    created_at = models.DateTimeField( auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def full_name(self):
        return f'{self.first_name} {self.last_name}'
    def full_address(self):
        return f'{self.address_line_1} {self.address_line_2}'

    def __str__(self):
        return self.first_name
    
class OrderProduct(models.Model):
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL ,blank=True , null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey("product.Product", on_delete=models.CASCADE)
    variations = models.ManyToManyField("product.Variation",blank=True)
    quantity = models.IntegerField()
    product_price = models.FloatField()
    ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField( auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.name

orders/forms.py
from django import forms
from .models import Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name' , 'last_name' , 'phone' ,'zip_code' , 'email' , 'address_line_1' , 'address_line_2' , 'country' , 'state' , 'city' , 'order_note']

orders/views.py
from django.shortcuts import render,redirect
from carts.models import CartItem
from .forms import OrderForm
from .models import Order, Payment, OrderProduct
from product.models import Product
import datetime
import json
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.http import HttpResponse, JsonResponse
from django.utils import timezone
from django.urls import reverse
from django.contrib import messages


# Create your views here.


def place_order(request, total=0, quantity=0,):
    current_user = request.user
    # If the cart count is less than or equal to 0, then redirect back to shop
    cart_items = CartItem.objects.filter(user=current_user)
    cart_count = cart_items.count()
    if cart_count <= 0:
        return redirect(reverse('product:product_list'))
    
    grand_total = 0
    tax = 0
    for cart_item in cart_items:
        if cart_item.product.discount:
                total+=(cart_item.product.discount * cart_item.quantity)
                quantity+=cart_item.quantity
        else:
                total+=(cart_item.product.price * cart_item.quantity)
                quantity+=cart_item.quantity
    tax = (2 * total)/100
    grand_total = total + tax
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            # Store all the billing information inside Order table
            data = Order()
            data.user = current_user
            data.first_name = form.cleaned_data['first_name']
            data.last_name = form.cleaned_data['last_name']
            data.phone = form.cleaned_data['phone']
            data.zip_code = form.cleaned_data['zip_code']
            data.email = form.cleaned_data['email']
            data.address_line_1 = form.cleaned_data['address_line_1']
            data.address_line_2 = form.cleaned_data['address_line_2']
            data.country = form.cleaned_data['country']
            data.state = form.cleaned_data['state']
            data.city = form.cleaned_data['city']
            data.order_note = form.cleaned_data['order_note']
            data.order_total = grand_total
            data.tax = tax
            data.ip = request.META.get('REMOTE_ADDR')
            data.save()
            # Generate order number
            yr = int(datetime.date.today().strftime('%Y'))
            dt = int(datetime.date.today().strftime('%d'))
            mt = int(datetime.date.today().strftime('%m'))
            d = datetime.date(yr,mt,dt)
            current_date = d.strftime("%Y%m%d") #20210305
            order_number = current_date + str(data.id)
            data.order_number = order_number
            data.save()

            order = Order.objects.get(user=current_user, is_orderd=False, order_number=order_number)
            context = {
                'order': order,
                'cart_items': cart_items,
                'total': total,
                'tax': tax,
                'grand_total': grand_total,
            }
            return render(request, 'payment.html', context)
        else:
             messages.error(request, 'Pls, Add your Delivery info!')
             return redirect(reverse('carts:checkout'))
    else:
        return redirect(reverse('carts:checkout'))
    
def payments(request):
    body = json.loads(request.body)
    order = Order.objects.get(user=request.user, is_orderd=False, order_number=body['orderID'])
    # Store transaction details inside Payment model
    payment = Payment(
        user = request.user,
        payment_id = body['transID'],
        payment_method = body['payment_method'],
        payment_paid = order.order_total,
        status = body['status'],
    )
    payment.save()
    order.payment = payment
    order.is_orderd = True
    order.save()

    # Move the cart items to Order Product table
    cart_items = CartItem.objects.filter(user=request.user)

    for item in cart_items:
        orderproduct = OrderProduct()
        orderproduct.order_id = order.id
        orderproduct.payment = payment
        orderproduct.user_id = request.user.id
        orderproduct.product_id = item.product_id
        orderproduct.quantity = item.quantity
        if item.product.discount :
            orderproduct.product_price = item.product.discount
        else :
            orderproduct.product_price = item.product.price
        orderproduct.ordered = True
        orderproduct.save()

        cart_item = CartItem.objects.get(id=item.id)
        product_variation = cart_item.variations.all()
        orderproduct = OrderProduct.objects.get(id=orderproduct.id)
        orderproduct.variations.set(product_variation)
        orderproduct.save()


        # Reduce the quantity of the sold products
        product = Product.objects.get(id=item.product_id)
        product.stock -= item.quantity
        product.save()

    # Clear cart
    CartItem.objects.filter(user=request.user).delete()

    # Send order recieved email to customer
    '''
    mail_subject = 'Thank you for your order!'
    message = render_to_string('order_recieved_email.html', {
        'user': request.user,
        'order': order,
    })
    to_email = request.user.email
    send_email = EmailMessage(mail_subject, message, to=[to_email])
    send_email.send()
    '''
    # Send order number and transaction id back to sendData method via JsonResponse
    data = {
        'order_number': order.order_number,
        'transID': payment.payment_id,
    }
    return JsonResponse(data)



def order_complete(request):
    order_number = request.GET.get('order_number')
    transID = request.GET.get('payment_id')

    try:
        order = Order.objects.get(order_number=order_number, is_orderd=True)
        ordered_products = OrderProduct.objects.filter(order_id=order.id)

        subtotal = 0
        for i in ordered_products:
            subtotal += i.product_price * i.quantity

        payment = Payment.objects.get(payment_id=transID)

        context = {
            'order': order,
            'ordered_products': ordered_products,
            'order_number': order.order_number,
            'transID': payment.payment_id,
            'payment': payment,
            'subtotal': subtotal,
        }
        return render(request, 'order_complete.html', context)
    except (Payment.DoesNotExist, Order.DoesNotExist):
        return redirect('/')
    
    

orders/templates/order_complete.html
{% extends 'base.html' %}
{% load static %}
{% block body %}


<div class="container" style="margin-top: 50px;">
    <center><i class="fas fa-check-circle" style="font-size: 72px;margin-bottom: 20px;color: #28A745;"></i></center>
    <h2 class="text-center">Payment Successful</h2>

</div>

<div class="container"
    style="margin: 0 auto;width: 50%;padding: 50px;background: #f1f1f1;margin-top: 50px;margin-bottom: 50px;">
    <div class="row invoice row-printable">
        <div class="col-md-12">
            <!-- col-lg-12 start here -->
            <div class="panel panel-default plain" id="dash_0">
                <!-- Start .panel -->
                <div class="panel-body p30">
                    <div class="row">
                        <!-- Start .row -->
                        <div class="col-lg-6">
                            <!-- col-lg-6 start here -->
                            <a href="/" class="text-decoration-none">
                                <h1 class="mb-4 display-5 font-weight-semi-bold"><span
                                        class="text-primary font-weight-bold border border-white px-3 mr-1">E</span>{{myfooter.site_name}}
                                </h1>
                            </a>
                        </div>
                        <!-- col-lg-6 end here -->
                        <div class="col-lg-6">
                            <!-- col-lg-6 start here -->
                            <div class="invoice-from">
                                <ul class="list-unstyled text-right">
                                    <li><strong>Invoiced To</strong></li>
                                    <li>{{order.full_name}}</li>
                                    <li>{{order.full_address}}</li>
                                    <li>{{order.city}}, {{order.state}}</li>
                                    <li>{{order.country}}</li>
                                </ul>
                            </div>
                        </div>
                        <!-- col-lg-6 end here -->
                        <div class="col-lg-12">
                            <!-- col-lg-12 start here -->
                            <div class="invoice-details mt25">
                                <div class="well">
                                    <ul class="list-unstyled mb0">
                                        <li><strong>Order</strong> #{{order_number}}</li>
                                        <li><strong>Transaction ID</strong> {{transID}}</li>
                                        <li><strong>Order Date:</strong> {{order.created_at}}</li>
                                        <li><strong>Status:</strong> {{payment.status}}</li>
                                    </ul>
                                </div>
                            </div>

                            <div class="invoice-items">
                                <div class="table-responsive" style="overflow: hidden; outline: none;" tabindex="0">
                                    <table class="table table-bordered text-center mb-0">
                                        <thead class="bg-secondary text-dark">
                                            <tr>
                                                <th>Products</th>
                                                <th>Price</th>
                                                <th>Quantity</th>
                                            </tr>
                                        </thead>
                                        <tbody class="align-middle">
                                            {% for cart_item in ordered_products %}
                                            <tr>
                                                <td class="align-middle"><img src="{{cart_item.product.image.url}}"
                                                        alt="" style="width: 50px;">
                                                    {{cart_item}}<p class="text-muted small"><br>
                                                        {% if cart_item.variations.all %}
                                                        {% for item in cart_item.variations.all  %}
                                                        {{item.variation_category|capfirst}} :
                                                        {{item.variation_value|capfirst}}<br>
                                                        {% endfor %}
                                                        {% endif %}
                                                    </p>
                                                </td>
                                                {% if cart_item.product.discount %}
                                                <td class="align-middle">${{cart_item.product.discount}} x {{cart_item.quantity}}</td>
                                                {% else %}
                                                <td class="align-middle">${{cart_item.product.price}} x {{cart_item.quantity}}</td>
                                                {% endif %}
                                                <td class="align-middle">
                                                    <div class="input-group quantity mx-auto" style="width: 100px;">

                                                        <input type="text"
                                                            class="form-control form-control-sm bg-secondary text-center"
                                                            value="{{cart_item.quantity}}">

                                                    </div>
                                                </td>

                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="text-center">
                                <h5 class="text-center">Order SubTotal & Tax</h5>
                                <h6 class="text-center">${{subtotal}} + {{order.tax}}</h6>
                                <h5 class="text-center">Order Total</h5>
                                <h6 class="text-center">${{order.order_total}} USD</h6>
                            </div>
                            <br>
                            <div class="invoice-footer mt25">
                                <p class="text-center">Thank you for shopping with us!</p>
                                <br>
                                <div class="text-center">
                                    <a href="{% url 'product:product_list' %}" class="btn btn-primary">Shop more</a>
                                </div>
                            </div>
                        </div>
                        <!-- col-lg-12 end here -->
                    </div>
                    <!-- End .row -->
                </div>
            </div>
            <!-- End .panel -->
        </div>
        <!-- col-lg-12 end here -->
    </div>
</div>

{% endblock %}

orders/templates/order_recieved_email.html
{% autoescape off %}

Hi {{user.first_name}},

YOUR ORDER HAS BEEN RECIEVED

Order Number: {{order.order_number}}

{% endautoescape %}

orders/templates/payment.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="container-fluid bg-secondary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
        <h1 class="font-weight-semi-bold text-uppercase mb-3">Payment</h1>
        <div class="d-inline-flex">
            <p class="m-0"><a href="/">Home</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0">Payment</p>
        </div>
    </div>
</div>
<!-- Cart Start -->
<h4 class="text-center mb-10">Review Your Order and make payment</h4>
<div class="container-fluid pt-5">
    <div class="row px-xl-5">
        <div class="col-lg-8 table-responsive mb-5">
            <div class="card">
                <h5 class="card-header">Billing Address</h5>
                <div class="card-body">
                    <p class="card-text mb-0">{{order.full_name}}</p>
                    <p class="card-text mb-0">{{order.full_address}}</p>
                    <p class="card-text mb-0">{{order.city}} , {{order.state}}</p>
                    <p class="card-text mb-0">{{order.order.country}}</p>
                    <p class="card-text mb-0">{{order.phone}}</p>
                    <p class="card-text mb-0">{{order.zip_code}}</p>
                    <p class="card-text mb-0">{{order.email}}</p>
                    {% if order.order_note %}
                    <p class="card-text mb-0"><b>Order Note: </b>{{order.order_note}}</p>
                    {% endif %}

                </div>
            </div>
            <div class="card">
                <h5 class="card-header">Payment Method</h5>
                <div class="card-body">
                    <p class="card-text">Paypal</p>
                </div>
            </div>
            <div class="card">
                <h5 class="card-header">Review Product</h5>
                <table class="table table-bordered text-center mb-0">
                    <thead class="bg-secondary text-dark">
                        <tr>
                            <th>Products</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                        {% for cart_item in cart_items %}
                        <tr>
                            <td class="align-middle"><img src="{{cart_item.product.image.url}}" alt=""
                                    style="width: 50px;">
                                {{cart_item}}<p class="text-muted small"><br>
                                    {% if cart_item.variations.all %}
                                    {% for item in cart_item.variations.all  %}
                                    {{item.variation_category|capfirst}} :
                                    {{item.variation_value|capfirst}}<br>
                                    {% endfor %}
                                    {% endif %}
                                </p>
                            </td>
                            {% if cart_item.product.discount %}
                            <td class="align-middle">${{cart_item.product.discount}}</td>
                            {% else %}
                            <td class="align-middle">${{cart_item.product.price}}</td>
                            {% endif %}
                            <td class="align-middle">
                                <div class="input-group quantity mx-auto" style="width: 100px;">

                                    <input type="text" class="form-control form-control-sm bg-secondary text-center"
                                        value="{{cart_item.quantity}}">

                                </div>
                            </td>
                            <td class="align-middle">${{cart_item.sub_total}}</td>

                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-lg-4">
            <form class="mb-5" action="">
                <div class="input-group">
                    <input type="text" class="form-control p-4"  placeholder="Coupon Code">
                    <div class="input-group-append">
                        <button class="btn btn-primary">Apply Coupon</button>
                    </div>
                </div>
            </form>
            <div class="card border-secondary mb-5">
                <div class="card-header bg-secondary border-0">
                    <h4 class="font-weight-semi-bold m-0">Cart Summary</h4>
                </div>
                <div class="card-body">
                    <div class="d-flex justify-content-between mb-3 pt-1">
                        <h6 class="font-weight-medium">Subtotal</h6>
                        <h6 class="font-weight-medium">${{total}}</h6>
                    </div>
                    <div class="d-flex justify-content-between">
                        <h6 class="font-weight-medium">Shipping</h6>
                        <h6 class="font-weight-medium">${{tax}}</h6>
                    </div>
                </div>
                <div class="card-footer border-secondary bg-transparent">
                    <div class="d-flex justify-content-between mt-2">
                        <h5 class="font-weight-bold">Total</h5>
                        <h5 class="font-weight-bold">${{grand_total}}</h5>
                    </div>
                    <div id="paypal-button-container">
                        <!-- PayPal Button Will Load -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Cart End -->
<script>
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }

        return cookieValue;
    }


    var amount = "{{ grand_total }}"
    var url = "{% url 'orders:payments' %}"
    var csrftoken = getCookie('csrftoken');
    var orderID = "{{order.order_number}}"
    var payment_method = 'PayPal'
    var redirect_url = "{% url 'orders:order_complete' %}"


    // Render the PayPal button into #paypal-button-container
    paypal.Buttons({



        // Set up the transaction
        createOrder: function (data, actions) {
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: amount,
                    }
                }]
            });
        },

        // Finalize the transaction
        onApprove: function (data, actions) {
            return actions.order.capture().then(function (details) {
                // Show a success message to the buyer
                console.log(details);
                sendData();

                function sendData() {
                    fetch(url, {
                            method: "POST",
                            headers: {
                                "Content-type": "application/json",
                                "X-CSRFToken": csrftoken,
                            },
                            body: JSON.stringify({
                                orderID: orderID,
                                transID: details.id,
                                payment_method: payment_method,
                                status: details.status,
                            }),
                        })
                        .then((response) => response.json())
                        .then((data) => {
                            window.location.href = redirect_url + '?order_number=' + data
                                .order_number + '&payment_id=' + data.transID;
                        });
                }
            });
        }


    }).render('#paypal-button-container');
</script>

{% endblock %}