carts/urls.py
from django.urls import path
from . views import cart ,add_cart,remove_cart,remove_cart_item,checkout

app_name = 'carts'

urlpatterns = [
    path('', cart ,name = 'cart'),
    path('add_cart/<int:product_id>/', add_cart ,name = 'add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', remove_cart ,name = 'remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', remove_cart_item ,name = 'remove_cart_item'),
    path('checkout/', checkout ,name = 'checkout'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('',views.ProductList.as_view(),name='product_list'),
    path('orderd_by_rating/',views.product_list_orderd_by_rating,name='product_list_orderd_by_rating'),
    path('orderd_by_created/',views.product_list_orderd_by_created , name='product_list_orderd_by_created'),
    path('orderd_by_popularty/',views.product_list_orderd_by_papularty , name='product_list_orderd_by_papularty'),
    path('orderd_by_price/',views.product_list_orderd_by_price , name='product_list_orderd_by_price'),
    path('orderd_by_highest price/',views.product_list_orderd_by_price2 , name='product_list_orderd_by_price2'),
    path('search/' , views.Search.as_view() , name = 'search'),
    path('result/' , views.search , name = 'result'),
    path('<slug:product_slug>/',views.product_detail ,name='product_detail'),
    path('<int:id>/like_or_dislike',views.like_or_unlike , name='like'),
    path('category/<int:id>/' , views.ProductByCategory.as_view() , name='product_by_category'),
    path('tags/<str:slug>/' , views.ProductByTags.as_view() , name='product_by_tags'),
    path('brand/<str:slug>/' , views.ProductByBrand.as_view() , name='product_by_brand'),
    path('submit_review/<int:product_id>/',views.submit_review ,name='submit_review'),
    path('&product_by_price/' , views.product_by_price , name = 'product_by_price'),
    path('&product_by_variation/' , views.product_by_variation , name = 'product_by_variation'),
]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('' , include('settings.urls' , namespace='home')),
    path('product/' , include('product.urls',namespace='product')),
    path('cart/' , include('carts.urls' , namespace='carts')),
    path('orders/' , include('orders.urls' )),
]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator , MinValueValidator
from django.utils import timezone

# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField( max_length=50 , blank=True)
    date_added = models.DateField( auto_now_add=True)


    def __str__(self):
        return self.cart_id
    
class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE , null=True)
    product = models.ForeignKey("product.Product", on_delete=models.CASCADE)
    variations = models.ManyToManyField("product.Variation",blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE , null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)


    def sub_total(self):
        if self.product.discount:
            return self.product.discount * self.quantity
        else:
            return self.product.price * self.quantity

    def __str__(self):
        return str(self.product)
    

carts/forms.py
from django import forms

class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter Password',
        'class': 'input-group',
    }))

carts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from product.models import Product
from .models import Cart , CartItem
from django.http import HttpResponse
from product.models import Variation
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.utils.crypto import get_random_string
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.urls import reverse




def get_csrf_token():
    return get_random_string(128)

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request , product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id)
    if current_user.is_authenticated:
        product_variation = []
        if request.method == "POST":
            for item in request.POST:
                key = item
                value = request.POST[key]

                try :
                    variation = Variation.objects.get(product=product,variation_category__iexact=key , variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass


        is_cart_item_exists = CartItem.objects.filter(product=product , user=current_user).exists()
        if is_cart_item_exists :
            cart_item = CartItem.objects.filter(product=product , user=current_user)
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation=item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)
            
            if product_variation in ex_var_list:
                index=ex_var_list.index(product_variation)
                item_id=id[index]
                item = CartItem.objects.get(product=product , id=item_id)  
                item.quantity+=1
                item.save()
            else :
                item = CartItem.objects.create(product=product , quantity = request.POST['quantity'] , user=current_user)
                if len(product_variation)>0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        else :
            cart_item = CartItem.objects.create(
                product=product,
                quantity = request.POST['quantity'] , 
                user = current_user ,
            )
            if len(product_variation)>0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    else :
        product_variation = []
        if request.method == "POST":
            for item in request.POST:
                key = item
                value = request.POST[key]

                try :
                    variation = Variation.objects.get(product=product,variation_category__iexact=key , variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass

        try :
            cart = Cart.objects.get(cart_id=_cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id = _cart_id(request)
            )
        cart.save()

        is_cart_item_exists = CartItem.objects.filter(product=product , cart=cart).exists()
        if is_cart_item_exists :
            cart_item = CartItem.objects.filter(product=product , cart = cart)
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation=item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)
            
            if product_variation in ex_var_list:
                index=ex_var_list.index(product_variation)
                item_id=id[index]
                item = CartItem.objects.get(product=product , id=item_id)
                item.quantity+=1
                item.save()
            else :
                item = CartItem.objects.create(product=product , quantity = request.POST['quantity'] , cart=cart)
                if len(product_variation)>0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        else :
            cart_item = CartItem.objects.create(
                product=product,
                quantity = request.POST['quantity'] , 
                cart = cart ,
            )
            if len(product_variation)>0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()

        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

def remove_cart(request , product_id,cart_item_id):
    
    product = get_object_or_404(Product,id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product , user=request.user , id=cart_item_id)
        else :
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(product=product , cart=cart , id=cart_item_id)
        if cart_item.quantity > 0 :
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect('/cart')

def remove_cart_item(request , product_id, cart_item_id):
    
    product = get_object_or_404(Product,id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product , user=request.user , id=cart_item_id)
    else :
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(product=product , cart=cart , id=cart_item_id)
    cart_item.delete()
    
    return redirect('/cart')

@login_required(login_url='login')
def cart(request,total=0 ,quantity=0,cart_items=None ):
    try:
        tax = 0
        grand_total=0
        offer = 0
        if request.user.is_authenticated:
             cart_items = CartItem.objects.filter(user=request.user,is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart,is_active=True)
        for cart_item in cart_items:
            if cart_item.product.discount:
                total+=(cart_item.product.discount * cart_item.quantity)
                quantity+=cart_item.quantity
                offer = cart_item.product.discount / cart_item.product.price * 100
            else:
                total+=(cart_item.product.price * cart_item.quantity)
                quantity+=cart_item.quantity
        tax = (2 * total)/100
        grand_total = total+tax
    except Cart.DoesNotExist:
        pass
    context={
        'cart_items':cart_items,
        'total':total,
        'quantity':quantity,
        'tax':tax,
        'grand_total':grand_total,
        'offer':offer,
    }
    return render(request,'carts/cart.html',context)



@login_required(login_url='login')
def checkout(request,total=0 ,quantity=0,cart_items=None):
    try:
        tax = 0
        grand_total=0
        if request.user.is_authenticated:
             cart_items = CartItem.objects.filter(user=request.user,is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart,is_active=True)
        for cart_item in cart_items:
            if cart_item.product.discount:
                total+=(cart_item.product.discount * cart_item.quantity)

                quantity+=cart_item.quantity
            else:
                total+=(cart_item.product.price * cart_item.quantity)
                quantity+=cart_item.quantity
        tax = (2 * total)/100
        grand_total = total+tax
    except Cart.DoesNotExist:
        pass
    context={
        'cart_items':cart_items,
        'total':total,
        'quantity':quantity,
        'tax':tax,
        'grand_total':grand_total,
    }
    return render(request,'checkout/checkout.html',context)

carts/templates/carts/cart.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<!-- Page Header Start -->
<div class="container-fluid bg-secondary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
        <h1 class="font-weight-semi-bold text-uppercase mb-3">Shopping Cart</h1>
        <div class="d-inline-flex">
            <p class="m-0"><a href="/">Home</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0">Shopping Cart</p>
        </div>
    </div>
</div>
<!-- Page Header End -->
{% if not cart_items %}
<h2 class="text-center">Your Shoping Cart Is Empty</h2>
<div class="text-center">
    <a href="{% url 'product:product_list'%}" class="btn btn-primary px-3">Continue Shopping</a>
</div>
{% else %}
<!-- Cart Start -->
<div class="container-fluid pt-5">
    <div class="row px-xl-5">
        <div class="col-lg-8 table-responsive mb-5">
            <table class="table table-bordered text-center mb-0">
                <thead class="bg-secondary text-dark">
                    <tr>
                        <th>Products</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody class="align-middle">
                    {% for cart_item in cart_items %}
                    <tr>
                        <td class="align-middle"><img src="{{cart_item.product.image.url}}" alt="" style="width: 50px;">
                            {{cart_item}}<p class="text-muted small"><br>
                                {% if cart_item.variations.all %}
                                {% for item in cart_item.variations.all  %}
                                {{item.variation_category|capfirst}} :
                                {{item.variation_value|capfirst}}<br>
                                {% endfor %}
                                {% endif %}
                                {{cart_item.product.stock}} In Stock
                            </p>
                        </td>
                        {% if cart_item.product.discount %}
                        <td class="align-middle">${{cart_item.product.discount}}<br><h6 class="text-muted ml-2"><del>${{cart_item.product.price}}</del></h6></td>
                        
                        {% else %}
                        <td class="align-middle">${{cart_item.product.price}}</td>
                        {% endif %}
                        <td class="align-middle">
                            <div class="input-group quantity mx-auto" style="width: 100px;">
                                <div class="input-group-btn">
                                    <a href="{% url 'carts:remove_cart' cart_item.product.id  cart_item.id%}"
                                        class="btn btn-sm btn-primary btn-minus">
                                        <i class="fa fa-minus"></i>
                                    </a>
                                </div>
                                <input type="text" class="form-control form-control-sm bg-secondary text-center"
                                    value="{{cart_item.quantity}}">
                                {% if cart_item.quantity < cart_item.product.stock %}
                                <div class="input-group-btn">
                                    <form action="{% url 'carts:add_cart' cart_item.product.id %}" method="POST">
                                        {% csrf_token %}
                                        {% for item in cart_item.variations.all %}
                                        <input type="hidden" class="form-control form-control-sm bg-secondary text-center"
                                            name="{{ item.variation_category | lower }}"
                                            value="{{ item.variation_value | capfirst }}">
                                        {% endfor %}
                                        <button class="btn btn-sm btn-primary btn-plus" type="submit"> <i
                                                class="fa fa-plus"></i> </button>
                                    </form>
                                </div>
                                {% else %}
                                {% endif %}
                            </div>
                        </td>
                        <td class="align-middle">${{cart_item.sub_total}}</td>
                        <td class="align-middle"><a
                                href="{% url 'carts:remove_cart_item' cart_item.product.id cart_item.id%}"
                                onclick="return confirm('Are You Sure You Want To Delete This Item ?')"
                                class="btn btn-sm btn-primary"><i class="fa fa-times"></i></a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-lg-4">
            <form class="mb-5" action="" method="POST">
                {% csrf_token %}
                <div class="input-group">
                    <input type="text" class="form-control p-4" name="code" placeholder="Coupon Code">
                    <div class="input-group-append">
                        <button class="btn btn-primary">Apply Coupon</button>
                    </div>
                </div>
            </form>
            <div class="card border-secondary mb-5">
                <div class="card-header bg-secondary border-0">
                    <h4 class="font-weight-semi-bold m-0">Cart Summary</h4>
                </div>
                <div class="card-body">
                    <div class="d-flex justify-content-between mb-3 pt-1">
                        <h6 class="font-weight-medium">Subtotal</h6>
                        <h6 class="font-weight-medium">${{total}}</h6>
                    </div>
                    <div class="d-flex justify-content-between">
                        <h6 class="font-weight-medium">Shipping</h6>
                        <h6 class="font-weight-medium">${{tax}}</h6>
                    </div>
                </div>
                <div class="card-footer border-secondary bg-transparent">
                    <div class="d-flex justify-content-between mt-2">
                        <h5 class="font-weight-bold">Total</h5>
                        <h5 class="font-weight-bold">${{grand_total}}</h5>
                    </div>
                    <a href="{% url 'carts:checkout'%}" class="btn btn-block btn-primary my-3 py-3">Proceed To
                        Checkout</a>
                    <a href="{% url 'product:product_list'%}" class="btn btn-block btn-primary my-3 py-3">Continue
                        Shopping</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
<!-- Cart End -->
{% endblock body %}