accounts/urls.py
from django.urls import path
from . import views 

app_name = 'accounts'

urlpatterns = [
    path('signup' , views.signup , name='signup'),
    path('profile/' , views.profile , name='profile'),
    path('profile/edit' , views.edit_profile , name='edit_profile'),
    path('favorite/' , views.user_favourites , name='user_favourites'),
    path('orders/' , views.orders , name='orders'),
    path('order_detail/<int:order_id>/' , views.order_detail , name='order_detail'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),
]

carts/urls.py
from django.urls import path
from . views import cart ,add_cart,remove_cart,remove_cart_item,checkout

app_name = 'carts'

urlpatterns = [
    path('', cart ,name = 'cart'),
    path('add_cart/<int:product_id>/', add_cart ,name = 'add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', remove_cart ,name = 'remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', remove_cart_item ,name = 'remove_cart_item'),
    path('checkout/', checkout ,name = 'checkout'),
]

orders/urls.py
from django.urls import path
from .  import views

app_name = 'orders'

urlpatterns = [
    path('place_order/' , views.place_order , name='place_order'),
    path('payments/' , views.payments , name='payments'),
    path('order_complete/' , views.order_complete , name='order_complete'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('',views.ProductList.as_view(),name='product_list'),
    path('orderd_by_rating/',views.product_list_orderd_by_rating,name='product_list_orderd_by_rating'),
    path('orderd_by_created/',views.product_list_orderd_by_created , name='product_list_orderd_by_created'),
    path('orderd_by_popularty/',views.product_list_orderd_by_papularty , name='product_list_orderd_by_papularty'),
    path('orderd_by_price/',views.product_list_orderd_by_price , name='product_list_orderd_by_price'),
    path('orderd_by_highest price/',views.product_list_orderd_by_price2 , name='product_list_orderd_by_price2'),
    path('search/' , views.Search.as_view() , name = 'search'),
    path('result/' , views.search , name = 'result'),
    path('<slug:product_slug>/',views.product_detail ,name='product_detail'),
    path('<int:id>/like_or_dislike',views.like_or_unlike , name='like'),
    path('category/<int:id>/' , views.ProductByCategory.as_view() , name='product_by_category'),
    path('tags/<str:slug>/' , views.ProductByTags.as_view() , name='product_by_tags'),
    path('brand/<str:slug>/' , views.ProductByBrand.as_view() , name='product_by_brand'),
    path('submit_review/<int:product_id>/',views.submit_review ,name='submit_review'),
    path('&product_by_price/' , views.product_by_price , name = 'product_by_price'),
    path('&product_by_variation/' , views.product_by_variation , name = 'product_by_variation'),
]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('' , include('settings.urls' , namespace='home')),
    path('product/' , include('product.urls',namespace='product')),
    path('cart/' , include('carts.urls' , namespace='carts')),
    path('orders/' , include('orders.urls' )),
]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm




class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email',"password1","password2"]

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','email','first_name','last_name',]
    
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['phone_number','address','image','country','city','company','headline','about','address_line_1','address_line_2','fb_link','twitter_link','instagram_link','linked_in_link']

orders/forms.py
from django import forms
from .models import Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name' , 'last_name' , 'phone' ,'zip_code' , 'email' , 'address_line_1' , 'address_line_2' , 'country' , 'state' , 'city' , 'order_note']

accounts/views.py
from django.shortcuts import render , redirect , get_object_or_404
from .forms import SignupForm , UserForm , ProfileForm
from .models import Profile
from product.models import Product
from django.contrib.auth.models import User
from django.contrib.auth import authenticate , login 
from django.db.models import Count
from orders.models import Order , OrderProduct
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage
from django.urls import reverse
from django.contrib import messages



def signup(request):
    if request.method == "POST":
        form=SignupForm(request.POST)
        if form.is_valid():
            form.save()
            
            usernames = form.cleaned_data['username']
            passwords = form.cleaned_data["password1"]
            user = authenticate(username=usernames,password=passwords)
            login(request,user)

            return redirect('/accounts/profile')
            
    else:
        form=SignupForm()

    return render(request,'registration/signup.html',{'form':form})



def profile(request):
    profile=Profile.objects.get(user=request.user)
    orders = Order.objects.order_by('-created_at').filter(user_id=request.user.id,is_orderd=True)
    orders_count = orders.count()

    return render(request,'profile/profile.html',{'profile':profile,
                                                  'orders_count':orders_count,})


def edit_profile(requset):
    profile = Profile.objects.get(user=requset.user)
    if requset.method == "POST":
        user_form = UserForm(requset.POST , instance=requset.user)
        profile_form = ProfileForm(requset.POST,requset.FILES,instance=profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            myprofile = profile_form.save(commit=False)
            myprofile.user = requset.user
            myprofile.save()
            return redirect('/accounts/profile')
    else:
        user_form = UserForm(instance=requset.user)
        profile_form = ProfileForm(instance=profile)

    return render(requset,'profile/profile_edit.html',{
        'user_form':user_form,
        'profile_form':profile_form
    })

def forgotPassword(request):
    if request.method == 'POST':
        email = request.POST['email']
        if User.objects.filter(email=email).exists():
            user = User.objects.get(email__exact=email)

            # Reset password email
            current_site = get_current_site(request)
            mail_subject = 'Reset Your Password'
            message = render_to_string('registration/password_reset_email.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()

            messages.success(request, 'Password reset email has been sent to your email address.')
            return redirect('login')
        else:
            messages.error(request, 'Account does not exist!')
            return redirect(reverse('accounts:forgotPassword'))
    return render(request, 'registration/password_reset_form.html')

def resetpassword_validate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        request.session['uid'] = uid
        messages.success(request, 'Please reset your password')
        return redirect(reverse('accounts:resetPassword'))
    else:
        messages.error(request, 'This link has been expired!')
        return redirect('login')

def resetPassword(request):
    if request.method == 'POST':
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            uid = request.session.get('uid')
            user = User.objects.get(pk=uid)
            user.set_password(password)
            user.save()
            messages.success(request, 'Password reset successful')
            return redirect('login')
        else:
            messages.error(request, 'Password do not match!')
            return redirect(reverse('accounts:resetPassword'))
    else:
        return render(request, 'registration/resetPassword.html')
    

def user_favourites(request):
    user_favourites = Product.objects.filter(like=request.user).annotate(product_count=Count('like'))
    product_count = user_favourites.count()
    return render(request,'profile/user_favourite.html',{'user_favourites':user_favourites,
                                                         'product_count':product_count})

def orders(request):
    orders = Order.objects.filter(user=request.user,is_orderd=True).order_by('-created_at')
    context = {
        'orders':orders,
    }
    return render(request,'profile/orders.html',context)

def order_detail(request,order_id):
    profile=Profile.objects.get(user=request.user)
    orders = Order.objects.get(order_number=order_id)
    order_detail = OrderProduct.objects.filter(order__order_number=order_id)
    subtotal = 0
    for i in order_detail:
        subtotal += i.product_price * i.quantity
    context = {
        'profile':profile,
        'orders':orders,
        'order_detail':order_detail,
        'subtotal':subtotal,
    }
    return render(request,'profile/order_detail.html',context)

orders/views.py
from django.shortcuts import render,redirect
from carts.models import CartItem
from .forms import OrderForm
from .models import Order, Payment, OrderProduct
from product.models import Product
import datetime
import json
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.http import HttpResponse, JsonResponse
from django.utils import timezone
from django.urls import reverse
from django.contrib import messages


# Create your views here.


def place_order(request, total=0, quantity=0,):
    current_user = request.user
    # If the cart count is less than or equal to 0, then redirect back to shop
    cart_items = CartItem.objects.filter(user=current_user)
    cart_count = cart_items.count()
    if cart_count <= 0:
        return redirect(reverse('product:product_list'))
    
    grand_total = 0
    tax = 0
    for cart_item in cart_items:
        if cart_item.product.discount:
                total+=(cart_item.product.discount * cart_item.quantity)
                quantity+=cart_item.quantity
        else:
                total+=(cart_item.product.price * cart_item.quantity)
                quantity+=cart_item.quantity
    tax = (2 * total)/100
    grand_total = total + tax
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            # Store all the billing information inside Order table
            data = Order()
            data.user = current_user
            data.first_name = form.cleaned_data['first_name']
            data.last_name = form.cleaned_data['last_name']
            data.phone = form.cleaned_data['phone']
            data.zip_code = form.cleaned_data['zip_code']
            data.email = form.cleaned_data['email']
            data.address_line_1 = form.cleaned_data['address_line_1']
            data.address_line_2 = form.cleaned_data['address_line_2']
            data.country = form.cleaned_data['country']
            data.state = form.cleaned_data['state']
            data.city = form.cleaned_data['city']
            data.order_note = form.cleaned_data['order_note']
            data.order_total = grand_total
            data.tax = tax
            data.ip = request.META.get('REMOTE_ADDR')
            data.save()
            # Generate order number
            yr = int(datetime.date.today().strftime('%Y'))
            dt = int(datetime.date.today().strftime('%d'))
            mt = int(datetime.date.today().strftime('%m'))
            d = datetime.date(yr,mt,dt)
            current_date = d.strftime("%Y%m%d") #20210305
            order_number = current_date + str(data.id)
            data.order_number = order_number
            data.save()

            order = Order.objects.get(user=current_user, is_orderd=False, order_number=order_number)
            context = {
                'order': order,
                'cart_items': cart_items,
                'total': total,
                'tax': tax,
                'grand_total': grand_total,
            }
            return render(request, 'payment.html', context)
        else:
             messages.error(request, 'Pls, Add your Delivery info!')
             return redirect(reverse('carts:checkout'))
    else:
        return redirect(reverse('carts:checkout'))
    
def payments(request):
    body = json.loads(request.body)
    order = Order.objects.get(user=request.user, is_orderd=False, order_number=body['orderID'])
    # Store transaction details inside Payment model
    payment = Payment(
        user = request.user,
        payment_id = body['transID'],
        payment_method = body['payment_method'],
        payment_paid = order.order_total,
        status = body['status'],
    )
    payment.save()
    order.payment = payment
    order.is_orderd = True
    order.save()

    # Move the cart items to Order Product table
    cart_items = CartItem.objects.filter(user=request.user)

    for item in cart_items:
        orderproduct = OrderProduct()
        orderproduct.order_id = order.id
        orderproduct.payment = payment
        orderproduct.user_id = request.user.id
        orderproduct.product_id = item.product_id
        orderproduct.quantity = item.quantity
        if item.product.discount :
            orderproduct.product_price = item.product.discount
        else :
            orderproduct.product_price = item.product.price
        orderproduct.ordered = True
        orderproduct.save()

        cart_item = CartItem.objects.get(id=item.id)
        product_variation = cart_item.variations.all()
        orderproduct = OrderProduct.objects.get(id=orderproduct.id)
        orderproduct.variations.set(product_variation)
        orderproduct.save()


        # Reduce the quantity of the sold products
        product = Product.objects.get(id=item.product_id)
        product.stock -= item.quantity
        product.save()

    # Clear cart
    CartItem.objects.filter(user=request.user).delete()

    # Send order recieved email to customer
    '''
    mail_subject = 'Thank you for your order!'
    message = render_to_string('order_recieved_email.html', {
        'user': request.user,
        'order': order,
    })
    to_email = request.user.email
    send_email = EmailMessage(mail_subject, message, to=[to_email])
    send_email.send()
    '''
    # Send order number and transaction id back to sendData method via JsonResponse
    data = {
        'order_number': order.order_number,
        'transID': payment.payment_id,
    }
    return JsonResponse(data)



def order_complete(request):
    order_number = request.GET.get('order_number')
    transID = request.GET.get('payment_id')

    try:
        order = Order.objects.get(order_number=order_number, is_orderd=True)
        ordered_products = OrderProduct.objects.filter(order_id=order.id)

        subtotal = 0
        for i in ordered_products:
            subtotal += i.product_price * i.quantity

        payment = Payment.objects.get(payment_id=transID)

        context = {
            'order': order,
            'ordered_products': ordered_products,
            'order_number': order.order_number,
            'transID': payment.payment_id,
            'payment': payment,
            'subtotal': subtotal,
        }
        return render(request, 'order_complete.html', context)
    except (Payment.DoesNotExist, Order.DoesNotExist):
        return redirect('/')
    
    

accounts/templates/profile/orders.html
     {% extends 'base.html' %}
     {% load static %}
     {% block body %}

     <!-- Cart Start -->
    <div class="container-fluid pt-5">
        <div class="row px-xl-5">
            <div class="col-lg-12 table-responsive mb-5">
                <table class="table table-bordered text-center mb-0">
                    <thead class="bg-secondary text-dark">
                        <tr>
                            <th>order #</th>
                            <th>Billing Name</th>
                            <th>Phone</th>
                            <th>Order Total</th>
                            <th>Order Date</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                        {% for order in orders %}
                        <tr>
                            
                            <td class="align-middle"><a href="{% url 'accounts:order_detail' order.order_number %}">{{order.order_number}}</a></td>
                            <td class="align-middle">${{order.full_name}}</td>
                            <td class="align-middle">
                                {{order.phone}}
                            </td>
                            <td class="align-middle">${{order.order_total}}</td>
                            <td class="align-middle">{{order.created_at}}</td>
                           
                        </tr>
                         {% endfor %}
                    </tbody>
                </table>
            </div>
            
        </div>
    </div>
    <!-- Cart End -->

     {% endblock %}

accounts/templates/profile/profile_edit.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block body %}
<div class="container">
    <div class="col-md-6 mx-auto mt-5">
        <h2 style="text-align:center;">Edit Profile</h2>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form user_form %}
            {% bootstrap_form profile_form %}
            {% bootstrap_button button_type="submit" content="Edit Profile" %}
        </form>

    </div>
</div>
{% endblock body %}

accounts/templates/profile/user_favourite.html
     {% extends 'base.html' %}
     {% load static %}
     {% block body %}

     <!-- Page Header Start -->
     <div class="container-fluid bg-secondary mb-5">
         <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
             <h1 class="font-weight-semi-bold text-uppercase mb-3">Our Shop</h1>
             <div class="d-inline-flex">
                 <p class="m-0"><a href="/">Home</a></p>
                 <p class="m-0 px-2">-</p>
                 <p class="m-0">Shop</p>
             </div>
         </div>
     </div>
     <!-- Shop Product Start -->
     <div class="col-lg-12 col-md-12">
         <div class="row pb-4">
             <div class="col-12 pb-1">
                 <div class="d-flex align-items-center justify-content-between mb-4">
                     <form action="{% url 'product:product_list'%}">
                         <div class="input-group">
                             <input type="text" name="q" class="form-control" placeholder="Search by name">
                             <div class="input-group-append">
                                 <span class="input-group-text bg-transparent text-primary">
                                     <i class="fa fa-search"></i>
                                 </span>
                             </div>
                         </div>
                     </form>
                     <div class="dropdown ml-4">
                         <button class="btn border dropdown-toggle" type="button" id="triggerId" data-toggle="dropdown"
                             aria-haspopup="true" aria-expanded="false">
                             Sort by
                         </button>
                         <div class="dropdown-menu dropdown-menu-right" aria-labelledby="triggerId">
                             <a class="dropdown-item" href="{% url 'product:product_list_orderd_by_created'%}">Latest</a>
                                <a class="dropdown-item" href="{% url 'product:product_list_orderd_by_papularty'%}">Popularity</a>
                                <a class="dropdown-item" href="{% url 'product:product_list_orderd_by_rating'%}">Best Rating</a>
                                <a class="dropdown-item" href="{% url 'product:product_list_orderd_by_price'%}">Price, low to high</a>
                                <a class="dropdown-item" href="{% url 'product:product_list_orderd_by_price2'%}">Price, high to low</a>
                         </div>
                     </div>
                 </div>
             </div>
             {% for product in user_favourites  %}
             <div class="col-md-3">
                 <div class="card product-item border-0 mb-4">
                     <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                         <img class="img-fluid w-100" src="{{product.image.url}}" alt="">
                     </div>
                     <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                         <h6 class="text-truncate mb-3">{{product.name}}</h6>
                         <div class="d-flex justify-content-center">
                             {% if product.discount > 0 %}
                             <h6>${{product.discount}}</h6>
                             <h6 class="text-muted ml-2"><del>{{product.price}}</del></h6>
                             {% else %}
                             <h6>${{product.price}}</h6>
                             {% endif %}
                         </div>
                     </div>
                     <div class="card-footer d-flex justify-content-between bg-light border">
                         <a href="{{product.get_absolute_url}}" class="btn btn-sm text-dark p-0"><i
                                 class="fas fa-eye text-primary mr-1"></i>View
                             Detail</a>
                         {% if request.user in product.like.all %}
                         <a href="{% url 'product:like' product.id%}" class="btn btn-sm text-dark p-0"><svg
                                 xmlns="http://www.w3.org/2000/svg" height="1.5em" viewBox="0 0 512 512">
                                 <!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. -->
                                 <style>
                                     svg {
                                         fill: #e19898
                                     }
                                 </style>
                                 <path
                                     d="M47.6 300.4L228.3 469.1c7.5 7 17.4 10.9 27.7 10.9s20.2-3.9 27.7-10.9L464.4 300.4c30.4-28.3 47.6-68 47.6-109.5v-5.8c0-69.9-50.5-129.5-119.4-141C347 36.5 300.6 51.4 268 84L256 96 244 84c-32.6-32.6-79-47.5-124.6-39.9C50.5 55.6 0 115.2 0 185.1v5.8c0 41.5 17.2 81.2 47.6 109.5z" />
                             </svg></a>
                         {% else %}
                         <a href="{% url 'product:like' product.id%}" class="btn btn-sm text-dark p-0"><svg
                                 xmlns="http://www.w3.org/2000/svg" height="1.5em" viewBox="0 0 512 512">
                                 <!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. -->
                                 <style>
                                     svg {
                                         fill: #e17070
                                     }
                                 </style>
                                 <path
                                     d="M225.8 468.2l-2.5-2.3L48.1 303.2C17.4 274.7 0 234.7 0 192.8v-3.3c0-70.4 50-130.8 119.2-144C158.6 37.9 198.9 47 231 69.6c9 6.4 17.4 13.8 25 22.3c4.2-4.8 8.7-9.2 13.5-13.3c3.7-3.2 7.5-6.2 11.5-9c0 0 0 0 0 0C313.1 47 353.4 37.9 392.8 45.4C462 58.6 512 119.1 512 189.5v3.3c0 41.9-17.4 81.9-48.1 110.4L288.7 465.9l-2.5 2.3c-8.2 7.6-19 11.9-30.2 11.9s-22-4.2-30.2-11.9zM239.1 145c-.4-.3-.7-.7-1-1.1l-17.8-20c0 0-.1-.1-.1-.1c0 0 0 0 0 0c-23.1-25.9-58-37.7-92-31.2C81.6 101.5 48 142.1 48 189.5v3.3c0 28.5 11.9 55.8 32.8 75.2L256 430.7 431.2 268c20.9-19.4 32.8-46.7 32.8-75.2v-3.3c0-47.3-33.6-88-80.1-96.9c-34-6.5-69 5.4-92 31.2c0 0 0 0-.1 .1s0 0-.1 .1l-17.8 20c-.3 .4-.7 .7-1 1.1c-4.5 4.5-10.6 7-16.9 7s-12.4-2.5-16.9-7z" />
                             </svg></i></a>
                         {% endif %}
                     </div>
                 </div>
             </div>
             {% endfor %}
             {% if is_paginated %}
             <div class="col-12 pb-1">
                 <nav aria-label="Page navigation">
                     <ul class="pagination justify-content-center mb-3">
                         <li class="page-item disabled">
                             {% if page_obj.has_previous %}
                         <li class="page-item">
                             <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Next">
                                 <span aria-hidden="true">&laquo;</span>
                                 <span class="sr-only">Previous</span>
                             </a>
                         </li>
                         {% else %}
                         <a class="page-link" aria-label="Previous">
                             <span aria-hidden="true">&laquo;</span>
                             <span class="sr-only">Previous</span>
                         </a>
                         {% endif %}
                         </li>
                         {% for i in paginator.page_range  %}
                         {% if page_obj.number == i%}
                         <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
                         {% else %}
                         <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                         {% endif %}

                         {% endfor %}
                         {% if page_obj.has_next %}
                         <li class="page-item">
                             <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                                 <span aria-hidden="true">&raquo;</span>
                             </a>
                         </li>
                         {% else %}
                         <li class="page-item disabled">
                             <div class="page-link" aria-label="Next">
                                 <span aria-hidden="true">&raquo;</span>
                             </div>
                             {% endif %}
                         </li>
                     </ul>
                 </nav>
             </div>
             {% endif %}

         </div>
     </div>
     <!-- Shop Product End -->
     {% endblock body %}