carts/urls.py
from django.urls import path
from . views import cart ,add_cart,remove_cart,remove_cart_item,checkout

app_name = 'carts'

urlpatterns = [
    path('', cart ,name = 'cart'),
    path('add_cart/<int:product_id>/', add_cart ,name = 'add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', remove_cart ,name = 'remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', remove_cart_item ,name = 'remove_cart_item'),
    path('checkout/', checkout ,name = 'checkout'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('',views.ProductList.as_view(),name='product_list'),
    path('orderd_by_rating/',views.product_list_orderd_by_rating,name='product_list_orderd_by_rating'),
    path('orderd_by_created/',views.product_list_orderd_by_created , name='product_list_orderd_by_created'),
    path('orderd_by_popularty/',views.product_list_orderd_by_papularty , name='product_list_orderd_by_papularty'),
    path('orderd_by_price/',views.product_list_orderd_by_price , name='product_list_orderd_by_price'),
    path('orderd_by_highest price/',views.product_list_orderd_by_price2 , name='product_list_orderd_by_price2'),
    path('search/' , views.Search.as_view() , name = 'search'),
    path('result/' , views.search , name = 'result'),
    path('<slug:product_slug>/',views.product_detail ,name='product_detail'),
    path('<int:id>/like_or_dislike',views.like_or_unlike , name='like'),
    path('category/<int:id>/' , views.ProductByCategory.as_view() , name='product_by_category'),
    path('tags/<str:slug>/' , views.ProductByTags.as_view() , name='product_by_tags'),
    path('brand/<str:slug>/' , views.ProductByBrand.as_view() , name='product_by_brand'),
    path('submit_review/<int:product_id>/',views.submit_review ,name='submit_review'),
    path('&product_by_price/' , views.product_by_price , name = 'product_by_price'),
    path('&product_by_variation/' , views.product_by_variation , name = 'product_by_variation'),
]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('' , include('settings.urls' , namespace='home')),
    path('product/' , include('product.urls',namespace='product')),
    path('cart/' , include('carts.urls' , namespace='carts')),
    path('orders/' , include('orders.urls' )),
]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify 
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from accounts.models import Profile
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.db.models import Avg , Count




class Product(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='product/')
    stock = models.IntegerField()
    price = models.IntegerField(default=0)
    discount = models.FloatField(_(""))
    description = models.TextField(max_length=10000)
    like = models.ManyToManyField(User , blank=True,related_name='product_favourite')
    created_at = models.DateTimeField( default=timezone.now)
    category = models.ForeignKey('ProductCategory',verbose_name=('category'), on_delete=models.CASCADE ,default='')
    subcategory = models.ForeignKey("Subcategory" , on_delete=models.CASCADE ,default='')
    PRDBrand = models.ForeignKey('settings.Brand' ,related_name='product_brand', on_delete=models.CASCADE , blank=True, null=True ,verbose_name=_("Brand "))
    slug = models.SlugField(null=True,blank=True , unique=True)
    tags = TaggableManager()
    views = models.PositiveIntegerField(default=0)
    is_available = models.BooleanField(default=True)

    class Meta:
        ordering = ["name"]

    def save(self,*args, **kwargs):
        if not self.slug:
            self.slug=slugify(self.name)
        super(Product,self).save(*args,**kwargs)

    def offer(self):
        offer = 0
        if self.discount > 0:
            offer =int( 100 - (self.discount / self.price * 100))
        return offer
    
    def get_absolute_url(self):
        return reverse("product:product_detail", args=[self.slug])

    def __str__(self):
        return self.name
    
    def avr_review(self):
        reviews = ReviewRating.objects.filter(product=self , status=True).aggregate(average=Avg('rating'))
        avg =0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg
    
    def count_review(self):
        reviews = ReviewRating.objects.filter(product=self , status=True).aggregate(count=Count('rating'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count
    
    def product_count(self):
        products = Product.objects.all().filter(is_available=True)
        product_count = products.count()
        print(product_count)
        return product_count
    
    
class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager,self).filter(variation_category='color',is_active=True)
    
    def sizes(self):
        return super(VariationManager,self).filter(variation_category='size',is_active=True)

variation_category_choice=(
    ('color','color'),
    ('size','size'),
)

class Variation(models.Model):
    product = models.ForeignKey(Product,  on_delete=models.CASCADE)
    variation_category = models.CharField( max_length=200 , choices=variation_category_choice)
    variation_value = models.CharField( max_length=200 )
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(  auto_now_add=True)
    objects = VariationManager()

    def __str__(self):
        return self.variation_value

class ProductImages(models.Model):
    product = models.ForeignKey(Product,related_name='product_image',on_delete=models.CASCADE)
    image = models.ImageField(upload_to='productimages/')

    def __str__(self):
        return str(self.product)
    
class ProductCategory(models.Model):
    name = models.CharField(max_length=60)
    

    def __str__(self):
        return self.name
    
class Subcategory(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='subcategoryimages/',blank=True)

    def __str__(self):
        return self.name
    

class ReviewRating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    subject = models.CharField(max_length=500 , blank=True)
    review = models.TextField(max_length=500 , blank=True)
    rating = models.FloatField()
    ip = models.CharField( max_length=50 , blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField( auto_now_add=True)
    updated_at = models.DateTimeField( auto_now=True)

    def __str__(self):
        return self.subject

product/forms.py
from django import forms
from .models import ReviewRating

class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject' , 'review' , 'rating']

product/views.py
from django.shortcuts import render , get_object_or_404 , redirect
from django.views.generic import ListView , DetailView
from .models import Product , ReviewRating
from .models import  ProductCategory 
from django.db.models import Count
from django_filters.views import FilterView
from django.db.models.query_utils import Q
from django.http import HttpResponseRedirect
from accounts.models import Profile
from django.http import JsonResponse
from django.conf import settings
from django.views.generic.edit import FormMixin
from carts.models import Cart,CartItem
from carts.views import _cart_id
from settings.models import Brand
from django.contrib import messages
from .forms import ReviewForm
from orders.models import OrderProduct
from django_filters.views import FilterView
from django.db.models import Avg
from django.core.paginator import Paginator
from .filters import ProductFilter




# Create your views here.

class ProductList(FilterView):
    model = Product
    filterset_class = ProductFilter
    paginate_by = 9
    template_name = 'product/product_list.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = ProductCategory.objects.all()

        return context
    
    def get_queryset(self) :
        name = self.request.GET.get('q','')
        object_list = Product.objects.filter(
            Q(name__icontains = name) |
            Q(description__icontains = name)
        )
        return object_list

def like_or_unlike(request,id):
    product = Product.objects.get(id=id)

    if request.user in product.like.all():
        product.like.remove(request.user.id)
    
    else:
        product.like.add(request.user.id)
    
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

def product_list_orderd_by_rating(request):
    object_list = Product.objects.all().order_by('-reviewrating')
    paginator = Paginator(object_list, 9)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {'object_list': object_list,
               'page_obj':page_obj}
    return render(request, 'product/product_list.html', context)

def product_list_orderd_by_created(request):
    object_list = Product.objects.all().order_by('-created_at')
    paginator = Paginator(object_list, 9)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {'object_list': object_list,
               'page_obj':page_obj}
    return render(request , 'product/product_list.html' , context)
def product_list_orderd_by_papularty(request):
    object_list = Product.objects.all().order_by('-views')
    paginator = Paginator(object_list, 9)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {'object_list': object_list,
               'page_obj':page_obj}
    return render(request , 'product/product_list.html' , context)

def product_list_orderd_by_price(request):
    object_list = Product.objects.all().order_by('price')
    paginator = Paginator(object_list, 9)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {'object_list': object_list,
               'page_obj':page_obj}
    return render(request , 'product/product_list.html' , context)

def product_list_orderd_by_price2(request):
    object_list = Product.objects.all().order_by('-price')
    paginator = Paginator(object_list, 9)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {'object_list': object_list,
               'page_obj':page_obj}
    return render(request , 'product/product_list.html' , context)

class Search(ListView):
    model = Product
    paginate_by = 12
    template_name = 'product/home_search.html'
    def get_queryset(self) :
        q = self.request.GET.get('q')
        object_list = Product.objects.filter(
            Q(name__icontains = q) |
            Q(description__icontains = q))        
        return object_list
    
def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

def search(request):
    if is_ajax(request=request):
        product = request.POST.get('product')
        res = None
        # print(product)
        query = Product.objects.filter(name__icontains=product)
        # print(query)
        if len(query) > 0 and len(product) > 0:
            data = []
            for position in query:
                item = {
                    'id' : position.id,
                    'slug' : position.slug,
                    'name' : position.name,
                    'price' : position.price,
                    'image' : str(position.image.url)
                }
                data.append(item)
            res = data
        else:
            res = 'No Products Found ...'

        return JsonResponse({'data':res})
    return JsonResponse({})


class ProductByCategory(ListView):
    model = Product
    paginate_by = 12
    template_name = 'product/home_search.html'


    def get_queryset(self) :
        id = self.kwargs['id']
        object_list = Product.objects.filter(
            Q(subcategory__id__icontains = id)
        )
        return object_list
    
class ProductByBrand(ListView):
    model = Product
    paginate_by = 12
    template_name = 'product/home_search.html'


    def get_queryset(self) :
        slug = self.kwargs['slug']
        object_list = Product.objects.filter(
            Q(PRDBrand__BRDName__icontains = slug)
        )
        return object_list
    
class ProductByTags(ListView):
    model = Product
    paginate_by = 12
    template_name = 'product/home_search.html'


    def get_queryset(self) :
        slug = self.kwargs['slug']
        object_list = Product.objects.filter(
            Q(tags__name__icontains = slug)
        )
        return object_list

    
def product_by_price(request):
    products = Product.objects.all()
    categories = ProductCategory.objects.all().annotate(product_count=Count('product'))

    min_price = request.GET.get('min_price')
    max_price = request.GET.get('max_price')
    for product in products:
        if product.discount:
            if min_price:
                product = products.filter(discount__gte=min_price)

            if max_price:
                product = products.filter(discount__lte=max_price)
        else:
            if min_price:
                product = products.filter(price__gte=min_price)

            if max_price:
                product = products.filter(price__lte=max_price)
            
    context = {'products':product,
               'categories':categories}

    return render(request,'product/product_by_price.html',context)

def product_by_variation(request):
    products = Product.objects.all()
    variation_name = request.GET.get('variation_name')
    if variation_name:
        products = products.filter(variation__variation_value__icontains=variation_name)
    context = {'products':products}
    return render(request , 'product/product_by_price.html',context)

def product_detail(request,product_slug):
    try :
        single_product = Product.objects.get(slug=product_slug)
        in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(request),product=single_product).exists()
        reviews = ReviewRating.objects.filter(product_id=single_product.id , status=True)
        single_product.views+=1
        single_product.save()
        if request.user.is_authenticated:
            try:
                orderproduct = OrderProduct.objects.filter(user=request.user , product_id=single_product.id).exists()
            except OrderProduct.DoesNotExist:
                orderproduct = None
        else :
            orderproduct = None
        
        orderproduct_2 =  OrderProduct.objects.filter(  product_id=single_product.id)
        orderproduct_count = orderproduct_2.count()

    except Exception as e:
        raise e
    related = Product.objects.filter(subcategory=single_product.subcategory)[:3]

    context = {
        'single_product':single_product,
        'in_cart':in_cart,
        'related':related,
        'reviews':reviews,
        'orderproduct':orderproduct,
        'orderproduct_count':orderproduct_count,
    }
    return render(request,'product/product_detail.html',context)

def submit_review(request,product_id):
    url = request.META.get('HTTP_REFERER')
    if request.method =="POST":
        try:
            reviews = ReviewRating.objects.get(user__id=request.user.id , product__id=product_id)
            form = ReviewForm(request.POST , instance=reviews)
            form.save()
            messages.success(request,'Thank You , Your Review has been updated.')
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product_id = product_id
                data.user_id = request.user.id
                data.save()
                messages.success(request,'Thank You , Your Review has been submitted.')
                return redirect(url)
            

product/templates/product/product_list.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block body %}

<!-- Page Header Start -->
<div class="container-fluid bg-secondary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
        <h1 class="font-weight-semi-bold text-uppercase mb-3">Our Shop</h1>
        <div class="d-inline-flex">
            <p class="m-0"><a href="/">Home</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0">Shop</p>
        </div>
    </div>
</div>
<!-- Page Header End -->


<!-- Shop Start -->
<div class="container-fluid pt-5">
    <div class="row px-xl-5">
        <!-- Shop Sidebar Start -->
        <div class="col-lg-3 col-md-12">
            <!-- Color Start -->
            <div class="border-bottom mb-4 pb-4">
                <form method="GET" action="{% url 'product:product_by_variation'%}">
                    <h5 class="font-weight-semi-bold mb-4">Filter by Variations</h5>
                    <label for="variation_name">Variation Name:</label>
                    <input placeholder="Color or Size" class="form-control" type="text" name="variation_name"
                        value="{{ request.GET.variation_name }}"><br>

                    <button class="btn btn-primary col-12 mx-auto" type="submit">SEARCH</button>
                </form>
            </div>
            <!-- Color End -->

            <!-- Size Start -->
            <div class="mb-5">
                <h5 class="font-weight-semi-bold mb-4">Filter by Price</h5>
                <form action="{% url 'product:product_by_price' %}" method="GET">
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="min_price">Min Price:</label>
                            <input class="mr-2 form-control" type="text" name="min_price"
                                value="{{ request.GET.min_price }}">
                        </div>
                        <div class="form-group text-right col-md-6">
                            <label for="max_price">Max Price:</label>
                            <input class="mr-2 form-control" type="text" name="max_price"
                                value="{{ request.GET.max_price }}">
                        </div>
                    </div>
                    <button class="btn btn-block btn-primary">Apply</button>
                </form>
            </div>


        </div>
        <!-- Shop Sidebar End -->


        <!-- Shop Product Start -->
        <div class="col-lg-9 col-md-12">
            <div class="row pb-3">
                <div class="col-12 pb-1">
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        <!-- <form action="{% url 'product:product_list'%}"> -->
                        <div class="position-relative ">
                            <form action="" id="searchForm" autocomplete="off">
                                {% csrf_token %}
                                <div class="input-group">
                                    <input type="text" id="searchInput" class="form-control"
                                        placeholder="Search by name">
                                    <div class="input-group-append">
                                        <span class="input-group-text bg-transparent text-primary">
                                            <i class="fa fa-search"></i>
                                        </span>
                                    </div>
                                </div>
                            </form>
                            <div id="results" class="results-card not-visible ">test</div>
                        </div>
                        <div class="dropdown ml-4">
                            <button class="btn border dropdown-toggle" type="button" id="triggerId"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Sort by
                            </button>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="triggerId">
                                <a class="dropdown-item"
                                    href="{% url 'product:product_list_orderd_by_created'%}">Latest</a>
                                <a class="dropdown-item"
                                    href="{% url 'product:product_list_orderd_by_papularty'%}">Popularity</a>
                                <a class="dropdown-item" href="{% url 'product:product_list_orderd_by_rating'%}">Best
                                    Rating</a>
                                <a class="dropdown-item" href="{% url 'product:product_list_orderd_by_price'%}">Price,
                                    low to high</a>
                                <a class="dropdown-item" href="{% url 'product:product_list_orderd_by_price2'%}">Price,
                                    high to low</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% for product in page_obj  %}
                <div class="col-lg-4 col-md-6 col-sm-12 pb-1">
                    <div class="card product-item border-0 mb-4">

                        <div
                            class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                            <img class="img-fluid w-100" src="{{product.image.url}}" alt="">
                        </div>
                        <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                            <h6 class="text-truncate mb-3">{{product.name}}</h6>
                            {% if product.offer %}
                            <div class="product-badge2 bg-success border-default text-body">{{product.offer}}%OFF</div>
                            {% endif %}
                            {% if product.stock <= 0 %}
                            <div class="product-badge2 bg-secondary2 border-default text-body">Out of stock</div>
                            {% endif %}
                            <div class="d-flex justify-content-center">
                                {% if product.discount > 0 %}
                                <h6>${{product.discount}}</h6>
                                <h6 class="text-muted ml-2"><del>{{product.price}}</del></h6>
                                {% else %}
                                <h6>${{product.price}}</h6>
                                {% endif %}
                            </div>
                            <div class="rating-star">
                                <span>
                                    <i class="fa fa-star{% if product.avr_review < 0.5%}-o{% elif product.avr_review >= 0.5 and product.avr_review < 1%}-half-o{%endif%}"
                                        aria-hidden="true"></i>
                                    <i class="fa fa-star{% if product.avr_review < 1.5%}-o{% elif product.avr_review >= 1.5 and product.avr_review < 2%}-half-o{%endif%}"
                                        aria-hidden="true"></i>
                                    <i class="fa fa-star{% if product.avr_review < 2.5%}-o{% elif product.avr_review >= 2.5 and product.avr_review < 3%}-half-o{%endif%}"
                                        aria-hidden="true"></i>
                                    <i class="fa fa-star{% if product.avr_review < 3.5%}-o{% elif product.avr_review >= 3.5 and product.avr_review < 4%}-half-o{%endif%}"
                                        aria-hidden="true"></i>
                                    <i class="fa fa-star{% if product.avr_review < 4.5%}-o{% elif product.avr_review >= 4.5 and product.avr_review < 5%}-half-o{%endif%}"
                                        aria-hidden="true"></i>
                                </span>({{product.count_review}} reviews)
                            </div>
                        </div>
                        <div class="card-footer d-flex justify-content-between bg-light border">
                            <a href="{{product.get_absolute_url}}" class="btn btn-sm text-dark p-0"><i
                                    class="fas fa-eye text-primary mr-1"></i>View
                                Detail</a>
                            {% if request.user in product.like.all %}
                            <a href="{% url 'product:like' product.id%}" class="btn btn-sm text-dark p-0"><svg
                                    xmlns="http://www.w3.org/2000/svg" height="1.5em" viewBox="0 0 512 512">
                                    <!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. -->
                                    <style>
                                        svg {
                                            fill: #e19898
                                        }
                                    </style>
                                    <path
                                        d="M47.6 300.4L228.3 469.1c7.5 7 17.4 10.9 27.7 10.9s20.2-3.9 27.7-10.9L464.4 300.4c30.4-28.3 47.6-68 47.6-109.5v-5.8c0-69.9-50.5-129.5-119.4-141C347 36.5 300.6 51.4 268 84L256 96 244 84c-32.6-32.6-79-47.5-124.6-39.9C50.5 55.6 0 115.2 0 185.1v5.8c0 41.5 17.2 81.2 47.6 109.5z" />
                                </svg></a>
                            {% else %}
                            <a href="{% url 'product:like' product.id%}" class="btn btn-sm text-dark p-0"><svg
                                    xmlns="http://www.w3.org/2000/svg" height="1.5em" viewBox="0 0 512 512">
                                    <!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. -->
                                    <style>
                                        svg {
                                            fill: #e17070
                                        }
                                    </style>
                                    <path
                                        d="M225.8 468.2l-2.5-2.3L48.1 303.2C17.4 274.7 0 234.7 0 192.8v-3.3c0-70.4 50-130.8 119.2-144C158.6 37.9 198.9 47 231 69.6c9 6.4 17.4 13.8 25 22.3c4.2-4.8 8.7-9.2 13.5-13.3c3.7-3.2 7.5-6.2 11.5-9c0 0 0 0 0 0C313.1 47 353.4 37.9 392.8 45.4C462 58.6 512 119.1 512 189.5v3.3c0 41.9-17.4 81.9-48.1 110.4L288.7 465.9l-2.5 2.3c-8.2 7.6-19 11.9-30.2 11.9s-22-4.2-30.2-11.9zM239.1 145c-.4-.3-.7-.7-1-1.1l-17.8-20c0 0-.1-.1-.1-.1c0 0 0 0 0 0c-23.1-25.9-58-37.7-92-31.2C81.6 101.5 48 142.1 48 189.5v3.3c0 28.5 11.9 55.8 32.8 75.2L256 430.7 431.2 268c20.9-19.4 32.8-46.7 32.8-75.2v-3.3c0-47.3-33.6-88-80.1-96.9c-34-6.5-69 5.4-92 31.2c0 0 0 0-.1 .1s0 0-.1 .1l-17.8 20c-.3 .4-.7 .7-1 1.1c-4.5 4.5-10.6 7-16.9 7s-12.4-2.5-16.9-7z" />
                                </svg></i></a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}

                <div class="col-12 pb-1">
                    <nav aria-label="Page navigation">
                        <ul class="pagination justify-content-center mb-3">
                            <li class="page-item disabled">
                                {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Next">
                                    <span aria-hidden="true">&laquo;</span>
                                    <span class="sr-only">Previous</span>
                                </a>
                            </li>
                            {% else %}
                            <a class="page-link" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                            </a>
                            {% endif %}
                            </li>
                            {% for i in paginator.page_range  %}
                            {% if page_obj.number == i%}
                            <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
                            {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                            {% endif %}

                            {% endfor %}
                            {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <div class="page-link" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </div>
                                {% endif %}
                            </li>
                        </ul>
                    </nav>
                </div>


            </div>
        </div>
        <!-- Shop Product End -->
    </div>
</div>
<!-- Shop End -->

{% endblock body %}

<!--  <a href="{%url 'product:add-to-cart' product.id  %}" class="btn btn-sm text-dark p-0"><i
                                    class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</a> -->